name: Notify Linter Fail
description: Sends Telegram notification about linter failure

inputs:
  service:
    required: true
  message:
    default: "Run `mvn spotbugs:gui` locally for details."

runs:
  using: "composite"
  steps:
    - run: |
        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage \
          -d chat_id=${TELEGRAM_CHAT_ID} \
          -d text="*Linter failed* for *${{ inputs.service }}*\n\n${{ inputs.message }}" \
          -d parse_mode=Markdown
      shell: bash
      env:
        TELEGRAM_BOT_TOKEN: ${{ env.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ env.TELEGRAM_CHAT_ID }}
