services:
  auth-server:
    build: ./backend/AuthServer
    ports:
      - "8081:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - backend
  chat-server:
    build: ./backend/ChatServer
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: ${MONGODB_URI}
      SPRING_DATA_MONGODB_DATABASE: ${MONGODB_DATABASE}
    networks:
      - backend
  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - chat-server
      - auth-server
networks:
  backend:
    driver: bridge