services:
  frontend:
    build:
      context: ./client
      target: development
      args:
        VITE_WEBSOCKET_URL: ${VITE_WEBSOCKET_URL}
        VITE_GATEWAY_URL: ${VITE_GATEWAY_URL}
    ports:
      - "3001:5173"
    depends_on:
      - chat-service
      - auth-service
      - gateway
    volumes:
      - ./client:/code
      - /code/node_modules
    command: ["npm", "run", "dev"]
    networks:
      - backend
