server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - ${FRONTEND_URL}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: auth-service
          uri: ${AUTH_URL}
          predicates:
            - Path=/auth/**

        - id: chat-service
          uri: ${CHAT_URL}
          predicates:
            - Path=/chat/**
          filters:
            - PreserveHostHeader

