FROM maven:3.9.9-eclipse-temurin-21 AS builder
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests -Dspotbugs.skip=true spotbugs:spotbugs

FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app
COPY --from=builder /app/target/chat-0.0.1-SNAPSHOT.jar app.jar
CMD ["java", "-jar", "app.jar"]