name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_BACKEND_AUTH: ${{ secrets.DOCKER_USERNAME }}/nreaxchat-auth-service
  IMAGE_BACKEND_CHAT: ${{ secrets.DOCKER_USERNAME }}/nreaxchat-chat-service
  IMAGE_FRONTEND: ${{ secrets.DOCKER_USERNAME }}/nreaxchat-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Auth
        working-directory: ./backend/auth-service
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests


      - name: Build Chat
        working-directory: ./backend/chat-service
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Auth Docker image
        run: docker build -t ${{ env.IMAGE_BACKEND_AUTH }} ./backend/auth-service

      - name: Build Chat Docker image
        run: docker build -t ${{ env.IMAGE_BACKEND_CHAT }} ./backend/chat-service

      - name: Build Frontend Docker image
        run: docker build -t ${{ env.IMAGE_FRONTEND }} ./client

      - name: Push Auth image
        run: docker push ${{ env.IMAGE_BACKEND_AUTH }}

      - name: Push Chat image
        run: docker push ${{ env.IMAGE_BACKEND_CHAT }}

      - name: Push Frontend image
        run: docker push ${{ env.IMAGE_FRONTEND }}
